Suprcode/Zircon

.gitignore, Server/Envir/SEnvir.cs, Server/Models/PlayerObject.cs
=> New GM commands

Server/Models/Monsters/Companion.cs
Will now collect gold if companion inventory is full
=> Fix for companions

LibraryEditor/LMain.cs, LibraryEditor/LibraryEditor.csproj, LibraryEditor/Program.cs
Added in the ability to open the .ZI files directly, please note I had to rename the out-put binary name as you cannot have two programs of the same name to open different file types.
Added the Auto save too.
=> Added ability to open .ZI files directly.

Client/Controls/DXItemCell.cs, Client/Envir/CConnection.cs, Client/Scenes/GameScene.cs, Client/Scenes/Views/NPCDialog.cs, Library/Enum.cs, Library/Network/ClientPackets.cs, Library/Network/ServerPackets.cs, Server/Envir/SConnection.cs, Server/Envir/Translations/ChineseMessages.cs, Server/Envir/Translations/EnglishMessages.cs, Server/Envir/Translations/StringMessages.cs, Server/Models/PlayerObject.cs
=> Mir3 Accessory Refining

Client/Envir/CConnection.cs
Fixed a typo should be MainPartsStorage was MainPartStorage
=> Fix to main parts

Server/Views/BaseStatView.Designer.cs
Fix to allow entry to the class column to update base stats correctly
=> Base Stats Viewer

Client/Envir/CConnection.cs, Client/Scenes/GameScene.cs, Client/Scenes/Views/MainPanel.cs, Client/Scenes/Views/RankingDialog.cs, Library/Globals.cs, Library/Network/ServerPackets.cs, Server/Envir/SEnvir.cs, Server/Models/PlayerObject.cs
I copied this all over into github so maybe pull it first and check it compiles/ works.
=> Configurable Experience List

Server/DBModels/AccountInfo.cs, Server/Envir/SEnvir.cs
fix to prevent account packet spamming from an ip
=> account packet spamming fix

LibraryCore/SystemModels/MapInfo.cs, PatchManager/PMain.cs, Server/Views/MapInfoView.Designer.cs, Server/Views/MapInfoView.cs, ServerLibrary/Envir/Config.cs, ServerLibrary/Envir/Translations/ChineseMessages.cs, ServerLibrary/Envir/Translations/EnglishMessages.cs, ServerLibrary/Envir/Translations/StringMessages.cs, ServerLibrary/Models/ItemObject.cs, ServerLibrary/Models/Map.cs, ServerLibrary/Models/MapObject.cs
* Fix patch updater error at end process
* Allow to others player see your drop, by default is false, you can change this in the Server.ini:
[Items]
DropVisibleOtherPlayers=True
* Allow require class for enter to map
=> many changes

ServerLibrary/Models/ItemObject.cs, ServerLibrary/Models/MapObject.cs, ServerLibrary/Models/PlayerObject.cs
catch the drop of other players after a while.
* After 2m you can take the drop of your group members.
* After 5m you can take the drop from members of your same guild
* After 10m anyone can take the drop.
Only apply this logic if you have the config enabled in the Server.ini:
[Items]
DropVisibleOtherPlayers = True
The fix is also included:
[Vaytrex] Fix for Resurrection Skill cause server crash
=> Take drop of others players 

LibraryCore/MirDB/Session.cs, Server/Properties/licenses.licx, Server/SMain.cs, Server/Server.csproj, Server/Views/ConfigView.Designer.cs, Server/Views/ConfigView.cs, Server/Views/ConfigView.resx, Server/Views/SyncForm.Designer.cs, Server/Views/SyncForm.cs, Server/Views/SyncForm.resx, ServerLibrary/Envir/Config.cs, ServerLibrary/Envir/EmailService.cs, ServerLibrary/Envir/SEnvir.cs, ServerLibrary/Envir/WebServer.cs
In order to manage your server without interface, I have enabled the possibility of sending the database (System.db) that we have on our local server (where we carry out the tests) to the remote server. This way it is not necessary to upload the file by hand.
This requires configuring the following on the remote server:
[System]
AllowSystemDBSync = True
SyncKey = YourSuperMasterUltraSecretKey!
With this we have already activated the synchronization command on the remote server.
Now we will open our local server, and in the maintenance "Config" we will see a new button that says "Syncronization Remote DB"
We put our command server, by default:
http: // <your server ip>: 80 / Command /
The SyncKey
And we send our local database to the server,
In the prox. reboot will be done :)
=> Remote system db syncronization

LibraryEditor/LMain.Designer.cs, LibraryEditor/LMain.cs, LibraryEditor/LMain.resx, LibraryEditor/MLibrary.cs, LibraryEditor/MLibraryV2.cs, LibraryEditor/Mir3Library.cs, LibraryEditor/WTLLibrary.cs, LibraryEditor/WeMadeLibrary.cs
added functionality to merge in multiple libaries into existing
can add blank images to end of file
can inset blank images to current selection point
=> library editor changes

Client/Client.csproj, Client/Envir/CConnection.cs, Client/Envir/Config.cs, Client/Models/MapObject.cs, Client/Models/PlayerObject.cs, Client/Models/UserObject.cs, Client/Scenes/GameScene.cs, Client/Scenes/Views/CharacterDialog.cs, Client/Scenes/Views/CompanionDialog.cs, Client/Scenes/Views/CompanionFilterDialog.cs, Client/UserModels/WindowSetting.cs, LibraryCore/Globals.cs, LibraryCore/Network/ClientPackets.cs, LibraryCore/Network/ServerPackets.cs, ServerLibrary/DBModels/CharacterInfo.cs, ServerLibrary/DBModels/CompanionFilters.cs, ServerLibrary/Envir/SConnection.cs, ServerLibrary/Envir/SEnvir.cs, ServerLibrary/Models/Monsters/Companion.cs, ServerLibrary/Models/PlayerObject.cs
- Simple client config based drop highlight 
- Companion filter (can filter by class, rarity and item type)
=> Drop highlight + companion filter

LibraryCore/Network/Packet.cs
very simple, just as the code says
=> coding mistake fixing

LibraryCore/Libraries.cs
- Fix LibraryFile file reference issue
- Add Fmmap and HorseS
=> Fix library file reference issue

Client/Models/MapObject.cs, Launcher/Launcher.csproj, LibraryCore/Enum.cs, LibraryCore/FrameSet.cs, ServerLibrary/Models/MapObject.cs, ServerLibrary/Models/PlayerObject.cs
1- Added The New Beginning skill added to assassin neutral skills
2- GM Commands now works when server owner ticks isAdmin on character info
=> Added The New Beginning Skill to Sin - Fixed GM Commands 

Client/Client.csproj, Client/Envir/DXSound.cs
Credit to lilcooldoode for the original code on our own source, wanted to share this with the main source.
=> MP3 Audio Format

Client/Controls/DXItemCell.cs, Client/Envir/CConnection.cs, Client/Scenes/GameScene.cs, Client/Scenes/Views/ChatTab.cs, Client/Scenes/Views/ChatTextBox.cs, Client/Scenes/Views/NPCDialog.cs, LibraryCore/Globals.cs, LibraryCore/Network/ServerPackets.cs, ServerLibrary/Envir/SConnection.cs, ServerLibrary/Models/PlayerObject.cs
Use CTRL + Middle Mouse Button to link items to chat.
=> Item Linking in Chat

Client/Controls/DXItemCell.cs, Client/Models/MonsterObject.cs, Client/Models/NPCObject.cs, Client/Scenes/GameScene.cs, Client/Scenes/Views/CharacterDialog.cs, ServerLibrary/Envir/Commands/Command/Admin/GiveHorse.cs, ServerLibrary/Models/PlayerObject.cs
GIVEHORSE gm command
Fixed marriage label position
Allow consumables when on a horse
=> Small bug fixes

Client/Envir/CConnection.cs, Client/Scenes/Views/CharacterDialog.cs, Client/Scenes/Views/InventoryDialog.cs, Client/Scenes/Views/StorageDialog.cs, LibraryCore/Network/ClientPackets.cs, LibraryCore/Network/ServerPackets.cs, ServerLibrary/Envir/SConnection.cs, ServerLibrary/Models/PlayerObject.cs
Added Inventory/Storage item sort button
Added Inventory Trash button
=> Added Inventory sort/trash buttons

LibraryCore/SystemModels/InstanceInfo.cs, LibraryCore/SystemModels/RespawnInfo.cs, Server/SMain.cs, Server/Views/InstanceInfoView.Designer.cs, Server/Views/RespawnInfoView.Designer.cs, Server/Views/RespawnInfoView.resx, ServerLibrary/Envir/SEnvir.cs, ServerLibrary/Models/Map.cs
Allows instances to have specific respawns, independant from the source map
=> Added RespawnIndex to Instances/Respawns (Credits to CheekyVimto)

Client/Controls/DXColourControl.cs, Client/Controls/DXConfigWindow.cs, Client/Controls/DXLabel.cs, Client/Envir/CConnection.cs, Client/Envir/Config.cs, Client/Envir/Translations/ChineseMessages.cs, Client/Envir/Translations/EnglishMessages.cs, Client/Envir/Translations/StringMessages.cs, Client/Scenes/Views/BeltDialog.cs, Client/Scenes/Views/ChatOptionsDialog.cs, Client/Scenes/Views/ChatTab.cs, ServerLibrary/Models/PlayerObject.cs
Fix reverse chat list location
Fix belt slots not removing
Remove trashed item from belt
Allow chat text backgrounds to be customised
=> Various Bug Fixes + Chat Text customising

LibraryCore/SystemModels/MovementInfo.cs, Server/Views/MovementInfoView.Designer.cs, Server/Views/MovementInfoView.resx, ServerLibrary/Models/Map.cs
Revert NeedSpawn logic, add new NeedHole bool
=> Revert NeedSpawn logic, add new NeedHole bool
